#!/usr/bin/env bash

set -e

if [[ $(hostname) == 'andrew-laptop' ]]; then CONFIG="laptop.install.yaml"
elif [[ $(hostname) == 'andrew-desktop-arch' ]]; then CONFIG="desktop.install.yaml"
else CONFIG="install.conf.yaml"
fi

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
