set tabstop=4
set softtabstop=0
set shiftwidth=0
set noexpandtab
set copyindent
set preserveindent

set autoindent
set cindent
set cinoptions+=:0 " do not indent 'case x:'

runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin indent on

let mapleader=","

set incsearch
set hlsearch
nnoremap <Leader><Space> :nohlsearch<CR>

highlight ExtraWhitespace ctermbg=red
match ExtraWhitespace /\s\+$\| \+\ze\t\|[^\t]\zs\t\+/
nnoremap <Leader>wf :match ExtraWhitespace //<CR>

" highlight the 81th column on long lines
2mat ErrorMsg '\%81v.'

cmap w!! w !sudo tee > /dev/null %

nnoremap <Leader>in :.-1read ~/Templates/

call Preamble#Enable('c,cpp,py')
nnoremap <Leader>fc :call Preamble#Fold()<CR>
