set tabstop=4
set softtabstop=0
set shiftwidth=0
set noexpandtab
set copyindent
set preserveindent

set autoindent
set cindent
set cinoptions+=:0 " do not indent 'case x:'

runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin indent on

let mapleader=","

set incsearch
set hlsearch
nnoremap <Leader><Space> :nohlsearch<CR>

if exists("less_mode") == 0
  highlight ExtraWhitespace ctermbg=red
  match ExtraWhitespace /\s\+$\| \+\ze\t\|[^\t]\zs\t\+/
  nnoremap <Leader>wf :match ExtraWhitespace // <Bar> :unmap <Leader>wf<CR>

  " highlight the 81th column on long lines
  2match ErrorMsg '\%81v.'
endif

cmap w!! w !sudo tee > /dev/null %

nnoremap <Leader>in :.-1read ~/Templates/

call Preamble#Enable('c,cpp,python')
nnoremap <Leader>fc :call Preamble#Fold()<CR>

let g:easytags_async = 1
let g:easytags_auto_highlight = 0
let g:easytags_events = ['BufWritePost']
nnoremap <Leader>tu :UpdateTags 
nnoremap <Leader>th :HighlightTags<CR>

nnoremap <C-n> :NERDTreeToggle<CR>
